apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: rbd-data0
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated:
    size: 1
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: cephfs-data0
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated:
    size: 1