apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nix-store
  namespace: buildkit
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: rook-cephfs