apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: suwayomi-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-static
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: suwayomi-media
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-static
  resources:
    requests:
      storage: 20Gi