apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-storage
  namespace: seafile
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 5Gi