apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: media
spec:
  selector:
    app: mariadb
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mariadb
  type: ClusterIP