apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./infrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  namespace: infrastructure
  dependsOn:
    - name: flux-system
  resources:
    - namespace.yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./infrastructure/metallb
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  namespace: metallb-system
  dependsOn:
    - name: infrastructure