apiVersion: v1
kind: Service
metadata:
  name: vllm-engine
  namespace: llm
spec:
  selector:
    app: vllm-engine
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP