apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-gateway-config-map
  namespace: envoy-gateway-system
data:
  values.yaml: |-
    service:
      type: LoadBalancer
      loadBalancerIP: "10.0.0.248"
      ports:
        - name: http
          port: 80
          targetPort: 80
        - name: https
          port: 443
          targetPort: 443