apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  chart:
    spec:
      chart: envoy-gateway
      version: 1.4.1
      sourceRef:
        kind: HelmRepository
        name: envoy-gateway
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: envoy-gateway
  valuesFrom:
  - kind: ConfigMap
    name: envoy-gateway-config-map
    valuesKey: values.yaml