apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  chart:
    spec:
      chart: gateway-helm
      version: 0.0.0-latest
      sourceRef:
        kind: HelmRepository
        name: envoy-gateway
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: envoy-gateway
  valuesFrom:
  - kind: ConfigMap
    name: envoy-gateway-config-map
    valuesKey: values.yaml