apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: authentik-ext-auth
  namespace: envoy-gateway-system
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: sonarr-https-route
      namespace: media
  extAuth:
    failOpen: false
    headersToExtAuth:
      - X-Forwarded-Host
      - X-Forwarded-Proto
      - X-Forwarded-For
      - Authorization
      - Cookie
    http:
      backendRefs:
        - group: ""
          kind: Service
          name: ak-outpost-authentik-embedded-outpost
          namespace: authentik
          port: 9000
      path: /outpost.goauthentik.io/auth/traefik
      headersToBackend:
        - X-authentik-username
        - X-authentik-groups
        - X-authentik-entitlements
        - X-authentik-email
        - X-authentik-name
        - X-authentik-uid
        - X-authentik-jwt
        - X-authentik-meta-jwks
        - X-authentik-meta-outpost
        - X-authentik-meta-provider
        - X-authentik-meta-app
        - X-authentik-meta-version