apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oglesby-io
  namespace: cert-manager
  labels:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "longhorn-system"
spec:
  secretName: oglesby-io-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.oglesby.io"
  dnsNames:
  - "oglesby.io"
  - "*.oglesby.io"