apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oglesby-io
  namespace: cert-manager
spec:
  secretName: oglesby-io-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.oglesby.io"
  dnsNames:
  - "oglesby.io"
  - "*.oglesby.io"