apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oglesby-io
  namespace: cert-manager
spec:
  secretName: oglesby-io-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.oglesby.io"
  dnsNames:
  - "oglesby.io"
  - "*.oglesby.io"
---
apiVersion: v1
kind: Secret
metadata:
  name: oglesby-io-tls
  namespace: cert-manager
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "longhorn-system"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
type: kubernetes.io/tls