apiVersion: v1
kind: Pod
metadata:
  name: talos-debug
  namespace: kube-system
spec:
  nodeName: talos-4m3-8nj
  securityContext:
    runAsUser: 0
  containers:
  - name: talos-debug
    image: alpine:edge
    imagePullPolicy: Always
    command: ["sh", "-c", "echo 'host debug pod ready'; sleep 36000"]
    securityContext:
      privileged: true
    volumeMounts:
    - name: hostroot
      mountPath: /host
  volumes:
  - name: hostroot
    hostPath:
      path: /
      type: Directory