apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn
spec:
  chart:
    spec:
      chart: longhorn
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: longhorn
  valuesFrom:
  - kind: ConfigMap
    name: longhorn-helm-chart-value-overrides
    valuesKey: values.yaml