apiVersion: v1
kind: Secret
metadata:
    name: seafile-secret
type: Opaque
data:
    JWT_PRIVATE_KEY: ENC[AES256_GCM,data:8N/e369BoFWVvx6a0V5LWSrMvRISqoittrfMep3lNmKHcB/0QVM2uQ==,iv:li0AkmpCUqZ5IE+/PK7IIwcdFqwS/MVAZKbcOapISYM=,tag:rt2IudJB0NR6bTFe3EbRFA==,type:str]
    SEAFILE_MYSQL_DB_PASSWORD: ENC[AES256_GCM,data:8eHJ9rl6bBOYkVqOpsByC9zx43r+2cC3imBKjjNbq74=,iv:un/V9/Uv6z2i21cMAIEfIOsiSoWb30F2q3oPbJl1TfQ=,tag:96eb6B+qUVDT8TAnTMTE4w==,type:str]
    INIT_SEAFILE_ADMIN_PASSWORD: ENC[AES256_GCM,data:y2KcRuyEvwonf4yZNtg=,iv:RCEPz28IzKFxLjTOXiMVgpC+10d0TYHcYmaYuL4EyTU=,tag:jlJ6RjRKybndj6x5l+3jGQ==,type:str]
    INIT_SEAFILE_MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:bsaD8J8wB/iRH5c1T/8odzdB+6oUe0ZV7CQHY9hKJ20=,iv:quyIWBckEiyt1feCPCV/JB8v0yD8SZ/mFHRs/TuBu4k=,tag:OUk/oPpK4164rY/AurmSZA==,type:str]
    S3_SECRET_KEY: ""
    S3_SSE_C_KEY: ""
    REDIS_PASSWORD: ""
    INIT_SEAFILE_ADMIN_EMAIL: ENC[AES256_GCM,data:QDMve5XdZdaje1LzFhSgmBv/6HWcvInwldBK,iv:Chws7CbTCVgjCY/dA8kkeP1NHTnG4BnCaE5pbDudVJQ=,tag:xbu1nmTO4amXXfQS4FzKAA==,type:str]
sops:
    age:
        - recipient: age1mvx2tgja4uztmjrdnfp5m2vlf3j7saj9lynzvyauhmrjvkzu2u4s7sf387
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlMysxMUp2V1JVQnZMTkpK
            eGpsMC9VLy9vYi80a0ZsSUF1UjZXd1BIbHg4CjJURmJFVUlydjNzaEtFQ250OG5w
            VzVjekJZYkQ5TjU1RHprOUd6VmlwdzQKLS0tIDdYSTI1aktsdncwdmg3MkUrdHpi
            ZURYaDFUb2JWU1NuTXlkVGhNSEs4TDAKivMSEQ5cwPqR0Hdup9vCyWffnzOm5Xdu
            Au0Oa/Z5SXDzZfUPFhV8Ok4U1/g4kg/pgqCsH4liTisgQr/bgkL5Iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-07T02:01:05Z"
    mac: ENC[AES256_GCM,data:JffGfg/Mp2YjLWg0tFl06YrVD/ZYF9eLYqUOXRh3zzjb4XHv0y+dd/yTnFFFXItf6gbJhTcX8k4TyF3ujg55wKQO1OT8YAnc2NyoFbyI6SV7LD6pwUXWUgPbVym6yTZXTyDdzfwsXW4kpKW2HQ75TnT9c5TCs1YPBzooONODg9I=,iv:Ed2QtafX0WNGyQsNJZobFUVB55dgN3AIS9SGfpOjGhk=,tag:nrD7MfUGlRABluRx2uLVlA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
