apiVersion: v1
kind: Secret
metadata:
    name: seafile-secrets
    namespace: seafile
type: Opaque
data:
    JWT_PRIVATE_KEY: ENC[AES256_GCM,data:gksHDOTY9bGcWKlRG8GsWZjbrlwAfYSi1KT9RRWzw8UNqAqHmhoVEw==,iv:uORSXddhxoI9JuTCpabMnwbaz5Yf6c75ACinN+hQn2s=,tag:HlniZXW00diR2nERpneD9w==,type:str]
    SEAFILE_MYSQL_DB_PASSWORD: ENC[AES256_GCM,data:lgg4WrB9/pBzXtGUllSCfQQzFlmFaRXMJ6adkPfQqqU=,iv:9EBhuiA/oAg8d3B8ceR7c2yc0TSFWeTJ9NrdW/w6Sjw=,tag:nkhRNSSpFmYSLPtY/4UiOQ==,type:str]
    INIT_SEAFILE_ADMIN_PASSWORD: ENC[AES256_GCM,data:DcOJQ7BsR1BhIuKPY5g=,iv:cspCEX7XDEq1iSX/leO141G7vvbGQXmUSTssRCnhtMY=,tag:W9/KudwbzV9O6jQq51wUXw==,type:str]
    INIT_SEAFILE_MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:s1cEmdd34TAhklBv1VQpTRG7CTAIcKGRf73TOoD9EUI=,iv:EHcMbPZ/weFl2R0m/Z8yMqG2nQgypj6FA6N1a+2y7WM=,tag:llM6OJORKVzcIls/77xEqQ==,type:str]
    S3_SECRET_KEY: ""
    S3_SSE_C_KEY: ""
    REDIS_PASSWORD: ""
    INIT_SEAFILE_ADMIN_EMAIL: ENC[AES256_GCM,data:Atq0xPeP97AiZVHap8F4laDtszFMNzGbDwCC,iv:o/uhr3AII5PRSwiStbcKye11Ivc9fj3eXMACpK+Ne2U=,tag:gogoSI9ZcqoBti8H00mGVg==,type:str]
sops:
    age:
        - recipient: age1mvx2tgja4uztmjrdnfp5m2vlf3j7saj9lynzvyauhmrjvkzu2u4s7sf387
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBOHpoajBUTEpRYmM5K1g4
            MHhUbUhHNUxGS2c0Z010Lzc3WHdGd2tjY3lvClcxcm1EZzIxVXR6RDBDc3NoVW9o
            Ym5DbTNUVFhiZTV3MTdFU3BvZFM2Q2sKLS0tIFNCOUlMMjM3UU9WbGtSRkU5NnZC
            amI4cHpSclJaaUtLdnBzVWVrNEZzRncKSqKp9sN+300PS3WI7djTD0ZWf3d490dt
            lqKNSjqyZMYy43AnZgIk6hk1IDEHgWM3N/fSGfaka/F63llNE1K46g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-07T02:31:12Z"
    mac: ENC[AES256_GCM,data:ZBHs7MYJwoAxkbUHOY9pOzjEUF9oXgsS0u5ZZUI1ipn70rrvrrgpvSJ9iWlEjUXCO5zaIJRrjUmi8rxCypsX8ElSa0mM2gtxdya0QufR7Izk6ruWAmwwxmhIsoF+bgwUF8XOvpoaWMgqinsI8n0LSLIBRfBYBFkZZh0mgaAJR6o=,iv:OyQlVYQhZmEEef+HVAkyzsIS6OT4fZSTSTo96sMLITE=,tag:3I+TT1KG6wJ1hjq8FStAIA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
