apiVersion: v1
kind: Secret
metadata:
    name: seafile-secrets
    namespace: seafile
type: Opaque
stringData:
    JWT_PRIVATE_KEY: ENC[AES256_GCM,data:gNW9eL+oJPzk2ivjNqclxh0l2cuaFqcveOgHR2qBJ0WNUdGWUAIE9w==,iv:V6TG8xlAXPlhr/bkiWEBd/Jqifc6TePyHbeQNZrXJTk=,tag:9hrW9s5Y+IIJopktvHwHdQ==,type:str]
    SEAFILE_MYSQL_DB_PASSWORD: ENC[AES256_GCM,data:xuYEgLO44byQRvPv1KEX9PhNN1SzgPZLRFolzoN7ATE=,iv:DiZL4r+f/zjfV7tZYOvj5RU1Xe64Gd/xgLsUQq3jiWY=,tag:CrTK2AlVl48/gIcglQbwWw==,type:str]
    INIT_SEAFILE_ADMIN_PASSWORD: ENC[AES256_GCM,data:yqGFQas8rI71BHpZOsU=,iv:2rj/qXf3jd9jy7CyYbpE2OJg7sXWW4ytCeVlsIa2SL0=,tag:q6SBH6/MtVI5fGdFssY7qQ==,type:str]
    INIT_SEAFILE_MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:EGxwNUbjl6XkJJFwanEFuG/vEzfwyLeC/GB60mQ4E0w=,iv:52uNme7aILFzHw8ra4xvQHRnzlESXuevChCfaVC2Vis=,tag:Iyeq7lreSpoTtRasRPw96Q==,type:str]
sops:
    age:
        - recipient: age1mvx2tgja4uztmjrdnfp5m2vlf3j7saj9lynzvyauhmrjvkzu2u4s7sf387
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqK2s2blN2djRKWUlNN2N3
            ODZxeWdtMGZSTkFEcFR0amF2VXdJRVByQUhVCkw2dHI1NEgyWkdVWTZUQWoxY1pQ
            c0RXNStPbnJQZjNZT28xbW93eU9reHcKLS0tIFNwcDhMQk9PQjlRT2hzQ1dwT1pr
            R2pOQkdVSW9jeTk1TkovWXlaNlJhWW8K7nzauOFosw+3WJWzGsZWZ4fR+0re8YF9
            7A7kY3s3+Bm3TNqyOy2uTTqUBErRdbtu0Y2LGC9v8kIvMnfuaJIvGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-05T00:28:12Z"
    mac: ENC[AES256_GCM,data:YZsMTF3OebPlwJ8uDg+V73lkcMsdKvWOqJ3xsuV9kZTA/oEUa1kHpuOC0BmIQzgO8j8LQy5el9YVb0OenVSOE5NdIoFinkfPsPkOTxZgHUR9P/IiPjuouKdqI+PztC9eZ0hwHuKYZ69O7akpSfiqPWXQ1iGdlGWQAuHDuIzkIM0=,iv:O7Lwm5Og242N5EZVdZ8a+N2aAzsG/s87832xgkxofJg=,tag:ssRiULhK7e7cFwj7+2Urjg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
