apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
  namespace: monitoring
spec:
  selector:
    app: prometheus
    component: server
  ports:
    - port: 80
      targetPort: 9090
  type: ClusterIP