apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzbget
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nzbget
  template:
    metadata:
      labels:
        app: nzbget
    spec:
      initContainers:
        - name: init-nzbget
          image: busybox
          command:
            - /bin/sh
            - -c
            - |
              set -e
              mkdir -p /init/downloads/complete /init/downloads/incomplete
              mkdir -p /init/media/movies /init/media/tvshows /init/media/leaving-soon
              chown -R 1000:1000 /init/downloads
              chown -R 1000:1000 /init/media
              chmod -R 777 /init/downloads
              chmod -R 777 /init/media
          volumeMounts:
            - name: media
              mountPath: /init
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 10.64.0.1
        options:
          - name: ndots
            value: "1"
      containers:
        - name: nzbget
          image: lscr.io/linuxserver/nzbget:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          ports:
            - containerPort: 6789
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "2000m"
              memory: "8Gi"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /downloads
              subPath: downloads
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: nzbget-config
        - name: media
          persistentVolumeClaim:
            claimName: media

