apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system
resources:
- namespace.yaml
- github.com/metallb/metallb/config/native?ref=v0.14.9
- ip_address_pool.yaml
- l2_advertisement.yaml
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: fluxcd
