apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway-system
  namespace: flux-system
spec:
  interval: 4m
  path: "./namespace/envoy-gateway-system"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m
  dependsOn:
    - name: kube-system
    - name: rook-ceph
    - name: cert-manager
    - name: reflector