apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-system
  namespace: flux-system
spec:
  interval: 5m
  path: "./namespace/kube-system"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m