apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-system
  namespace: flux-system
spec:
  interval: 5m
  path: "./metallb-system"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system