apiVersion: apps/v1
kind: Deployment
metadata:
  name: redbot
  namespace: automation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redbot
  template:
    metadata:
      labels:
        app: redbot
    spec:
      runtimeClassName: kata
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: jellyfin
          image: docker.io/phasecorex/red-discordbot:core
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: redbot-secrets
                  key: TOKEN
            - name: PREFIX
              value: "!"
          volumeMounts:
            - name: config
              mountPath: /data
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: redbot-config
