apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redbot-config
  namespace: automation
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi