apiVersion: v1
kind: Namespace
metadata:
  name: infrastructure
  labels:
    app.kubernetes.io/managed-by: fluxcd
---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    app.kubernetes.io/managed-by: fluxcd
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    app.kubernetes.io/managed-by: fluxcd