apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unmanic-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-static
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unmanic-temp
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-static
  resources:
    requests:
      storage: 40Gi