apiVersion: apps/v1
kind: Deployment
metadata:
  name: gluetun
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gluetun
  template:
    metadata:
      labels:
        app: gluetun
    spec:
      automountServiceAccountToken: false
      containers:
        - name: gluetun
          image: ghcr.io/qdm12/gluetun:latest
          ports:
            - containerPort: 8888
              protocol: TCP
            - containerPort: 8388
              protocol: TCP
            - containerPort: 8388
              protocol: UDP
            - containerPort: 53
              protocol: UDP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: SHADOWSOCKS
              value: "on"
            - name: VPN_SERVICE_PROVIDER
              value: "mullvad"
            - name: VPN_TYPE
              value: "wireguard"
            - name: SERVER_CITIES
              value: "Amsterdam"
            - name: OWNED_ONLY
              value: "yes"
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: gluetun-secrets
                  key: WIREGUARD_PRIVATE_KEY
            - name: WIREGUARD_ADDRESSES
              valueFrom:
                secretKeyRef:
                  name: gluetun-secrets
                  key: WIREGUARD_ADDRESSES
          securityContext:
            privileged: true
          volumeMounts:
            - name: config
              mountPath: /gluetun
            - name: dev-tun
              mountPath: /dev/net/tun
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: gluetun-config
        - name: dev-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
