apiVersion: v1
kind: Service
metadata:
  name: gluetun
  namespace: media
spec:
  selector:
    app: gluetun
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: gluetun-tcp1
    - port: 8388
      targetPort: 8388
      protocol: TCP
      name: gluetun-tcp2
    - port: 8388
      targetPort: 8388
      protocol: UDP
      name: gluetun-udp
  type: ClusterIP