apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emulatorjs-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emulatorjs-roms
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 500Gi