apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtorrent
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtorrent
  template:
    metadata:
      labels:
        app: rtorrent
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
        - name: init-rtorrent
          image: busybox
          command:
            - /bin/sh
            - -c
            - |
              set -e
              mkdir -p /init/downloads/complete /init/downloads/incomplete
              mkdir -p /init/media/movies /init/media/tvshows /init/media/leaving-soon
              cp /secrets/rpc.htpasswd /passwd/rpc.htpasswd
          volumeMounts:
            - name: media
              mountPath: /init
            - name: passwd
              mountPath: /passwd
            - name: rtorrent-credentials
              mountPath: /secrets/rpc.htpasswd
              subPath: rpc.htpasswd
              readOnly: true
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 10.64.0.1
        options:
          - name: ndots
            value: "1"
      containers:
        - name: rtorrent
          image: docker.io/crazymax/rtorrent-rutorrent:latest
          ports:
            - containerPort: 8080
            - containerPort: 8000
            - containerPort: 9000
            - containerPort: 50000
            - containerPort: 6881
              protocol: UDP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "2000m"
              memory: "8Gi"
          volumeMounts:
            - name: config
              mountPath: /data
            - name: media
              mountPath: /downloads
              subPath: downloads
            - name: passwd
              mountPath: /passwd
            - name: rtorrent-credentials
              mountPath: /secrets/rpc.htpasswd
              subPath: rpc.htpasswd
              readOnly: true

      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: rtorrent-config
        - name: media
          persistentVolumeClaim:
            claimName: media
        - name: passwd
          emptyDir: {}
        - name: rtorrent-credentials
          secret:
            secretName: rtorrent-secrets
            items:
              - key: rpc.htpasswd
                path: rpc.htpasswd