apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-crds
  namespace: flux-system
spec:
  interval: 1m
  path: "./metallb-system/crds"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system