apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: seafile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "100m"
          volumeMounts:
            - name: redis-data
              mountPath: /data
          args: ["--save", "", "--appendonly", "no"] # ephemeral setup
      volumes:
        - name: redis-data
          emptyDir: {}