apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: seafile
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  type: ClusterIP