apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heimdall-config
  namespace: heimdall
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 8Gi