apiVersion: cilium.io/v2
kind: CiliumEgressGatewayPolicy
metadata:
  name: media-egress
spec:
  selectors:
    - podSelector:
        matchExpressions:
          - {key: app, operator: In, values: [flaresolverr, qbittorrent, sabnzbd]}
          - {key: io.kubernetes.pod.namespace, operator: In, values: [media]}
  destinationCIDRs:
    - 0.0.0.0/0
  egressGateway:
    interface: wg0