apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: flux
resources:
  - namespace.yaml
  - pvc.yaml
  - ciliumegresspolicy.yaml
  - flaresolverr/
  - rtorrent/
  - nzbget/
  - prowlarr/
  - bazarr/
  - radarr/
  - sonarr/
  - jellyfin/
  - ersatztv/
  - tdarr/
  - jellyseerr/
  - jellystat/
  - janitorr/
  - requestrr/
  # - wizarr/
  - suwayomi/
