apiVersion: apps/v1
kind: Deployment
metadata:
  name: semgrep
  namespace: mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: semgrep
  template:
    metadata:
      labels:
        app: semgrep
    spec:
      containers:
        - name: semgrep
          image: ghcr.io/semgrep/mcp:latest
          ports:
            - containerPort: 8000
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "1"
              memory: "1Gi"