apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openhands-config
  namespace: llm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 20Gi