apiVersion: apps/v1
kind: Deployment
metadata:
  name: optillm
  namespace: llm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: optillm
  template:
    metadata:
      labels:
        app: optillm
    spec:
      containers:
        - name: optillm
          image: ghcr.io/codelion/optillm:latest-proxy
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "2"
              memory: "4Gi"