apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: radarr-https
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`radarr.oglesby.io`)
      kind: Rule
      services:
        - name: radarr
          port: 7878
  tls:
    certResolver: letsencrypt
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: radarr-http
  namespace: media
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`radarr.oglesby.io`)
      kind: Rule
      middlewares:
        - name: redirect-to-https
      services:
        - name: radarr
          port: 7878