apiVersion: apps/v1
kind: Deployment
metadata:
  name: suwayomi
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: suwayomi
  template:
    metadata:
      labels:
        app: suwayomi
    spec:
      containers:
        - name: suwayomi
          image: ghcr.io/suwayomi/tachidesk:latest
          command:
            - /bin/sh
            - -c
          args:
            - |
              set -e
              chown -R 1000:1000 /home/suwayomi/.local/share/Tachidesk
              chmod -R 777 /home/suwayomi/.local/share/Tachidesk
          ports:
            - containerPort: 4567
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: FLARESOLVERR_ENABLED
              value: "true"
            - name: FLARESOLVERR_URL
              value: "https://flaresolverr.oglesby.io"
          volumeMounts:
            - name: media
              mountPath: /home/suwayomi/.local/share/Tachidesk/downloads
            - name: config
              mountPath: /home/suwayomi/.local/share/Tachidesk
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: suwayomi-media
        - name: config
          persistentVolumeClaim:
            claimName: suwayomi-config
