apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: suwayomi-https
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`suwayomi.oglesby.io`)
      kind: Rule
      services:
        - name: suwayomi
          port: 4567
  tls: 
    secretName: oglesby-io-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: suwayomi-http
  namespace: media
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`suwayomi.oglesby.io`)
      kind: Rule
      middlewares:
        - name: redirect-to-https
      services:
        - name: suwayomi
          port: 4567