apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-config-map
  namespace: authentik
data:
  values.yaml: |-
    authentik:
        error_reporting:
            enabled: false
        # postgresql:
        #     password: ""
    server:
        ingress:
            ingressClassName: traefik
            enabled: false
            hosts:
                - authentik.oglesby.io
    postgresql:
        enabled: true
        #   auth:
        #     password: ""
    redis:
    enabled: true
      master:
          persistence:
          enabled: false
          resources:
          requests:
              memory: 256Mi
          limits:
              memory: 512Mi
          extraFlags:
          - "--save"
          - "\"\""
          - "--appendonly"
          - "no"