apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-config-map
  namespace: authentik
data:
  values.yaml: |-
      authentik:
        secret_key: "1tGmyxXBjwZZeLmTF8VSp264UnJv1LNlSNU04U15WKqUYttWkJ"
        error_reporting:
            enabled: false
        postgresql:
            password: "Xfv5x1TzCTVEmcwK2P6WBUNcTLU5mh1y"
      server:
          ingress:
              ingressClassName: traefik
              enabled: false
              hosts:
                  - authentik.oglesby.io
      postgresql:
          enabled: true
          auth:
              password: "Xfv5x1TzCTVEmcwK2P6WBUNcTLU5mh1y"
      redis:
          enabled: true