apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-config-map
  namespace: authentik
data:
  values.yaml: |-
      authentik:
        error_reporting:
          enabled: false
      server:
        ingress:
          ingressClassName: traefik
          enabled: false
          hosts:
            - authentik.oglesby.io
      postgresql:
        enabled: true
      redis:
        enabled: true