apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  chart:
    spec:
      chart: authentik
      version: 2025.2.4
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: authentik
  valuesFrom:
  - kind: ConfigMap
    name: authentik-config-map
    valuesKey: values.yaml
  values:
    authentik:
      existingSecret: authentik-secrets
      existingSecretKey: secret_key
      postgresql:
        existingSecret: authentik-secrets
        existingSecretKey: password

    postgresql:
      auth:
        existingSecret: authentik-secrets
        existingSecretKey: postgres-password
