apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik-http
  namespace: authentik
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`authentik.oglesby.io`)
      kind: Rule
      services:
      - name: authentik-server
        port: 80
      middlewares:
      - name: internal-whitelist
        namespace: traefik
      - name: redirect-https
        namespace: traefik
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik-https
  namespace: authentik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`authentik.oglesby.io`)
      kind: Rule
      middlewares:
        - name: internal-whitelist
          namespace: traefik
      services:
      - name: authentik-server
        port: 80
  tls: 
    secretName: oglesby-io-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik-auth-http
  namespace: authentik
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`auth.oglesby.io`) || HostRegexp(`{subdomain:[a-z0-9]+}.oglesby.io`) && PathPrefix(`/outpost.goauthentik.io/`)
      kind: Rule
      services:
      - name: ak-outpost-authentik-embedded-outpost
        port: 9000
      middlewares:
      - name: internal-whitelist
        namespace: traefik
      - name: redirect-https
        namespace: traefik
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik-auth-https
  namespace: authentik
spec:
  entryPoints:
    - websecure
  routes:
    - match:  Host(`auth.oglesby.io`) || HostRegexp(`{subdomain:[a-z0-9]+}.oglesby.io`) && PathPrefix(`/outpost.goauthentik.io/`)
      kind: Rule
      middlewares:
        - name: internal-whitelist
          namespace: traefik
      services:
      - name: ak-outpost-authentik-embedded-outpost
        port: 9000
  tls: 
    secretName: oglesby-io-tls
