apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
type: Opaque
stringData:
    secret_key: ENC[AES256_GCM,data:G2DH9rkv3wBdCO6EfWE4UoEq9G3WhHYJShs0q86aqCywR6TdjD6ZjroRcDzwEYVdiSo=,iv:7YmiKXVp6sMvz/iCYz9mH1/gmPNjYK1+PHXqNdMHpPU=,tag:ma4FEqzwPViDs0JFD/CduQ==,type:str]
    postgres-password: ENC[AES256_GCM,data:+/G8QGW1Sl3ABCbwFYxBtDv6rQcoQI07YPOiBjq1qaU=,iv:XndJbSy/6e8q3v0R1JPwDw1KVe/WZRUkZ6KzKcFJwNI=,tag:GDW8N06TVAhmuqJb9xYWvQ==,type:str]
sops:
    age:
        - recipient: age1mvx2tgja4uztmjrdnfp5m2vlf3j7saj9lynzvyauhmrjvkzu2u4s7sf387
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbGM4VU5oeGRDb1RKTTFw
            aWYxRGVVL2VqdnNCSXN3SXdaVDdrRjg5dnpZCmFJQmhramsxc2s1cWVBcytLV20r
            TWJvU1FYWTJWcTUzTlhyWnA5VUZIK28KLS0tIFJUNCs4clcxaGxBQ2lWNk9RT1hl
            aG9aZGh2U2ZYazZGeThPSkZvMXZUblkKnNxaTYI31qcAWby4PoA0fxcgmnbeGLql
            OUDo0qV1UpxuqsCvRjGq8y+dYM382qIwSlVoA24raZPGOseCFeRjzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-17T22:04:29Z"
    mac: ENC[AES256_GCM,data:WD1adEUVvpmYEqWiQHrtNPndhtXO6EPYB0Ki82ByW1JR5BoB+ORrpRsD23w0IUP+oxpe60rR9bm6P9n+q+CaEhaNMgLiDR+2me5A3Mf0NQB68KcqlbhkIt1XDy4CwT8jKLJHo9CgEe3TunUWc89+Bf6LmpX2fI+0L0l4cYUkmD4=,iv:W9MgOht8Pw/nxbeY4m6JvRh+mPuhJsiOohHYkgiNOPM=,tag:8BHfUeIGkdq/zesJgguPyg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
