apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-block
provisioner: openebs.io/local
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
  - matchLabelExpressions:
      - key: kubernetes.io/hostname
        values:
          - talos-4m3-8nj
parameters:
  blockdevice: /dev/sdb