apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: automation
  namespace: flux-system
spec:
  interval: 5m
  path: "./namespace/automation"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m