apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: flux
resources:
  - runtimeclass.yaml
  - coredns/
  - cilium/
  - egress-gw-helper/daemonset.yaml
  - intel-gpu-plugin/daemonset.yaml
  - kubelet-csr-approver/
  - metrics-server/
  - talos-debug/deployment.yaml