apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vector
  namespace: vector
spec:
  chart:
    spec:
      chart: vector
      version: 0.41.0
      sourceRef:
        kind: HelmRepository
        name: vector
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: vector
  valuesFrom:
  - kind: ConfigMap
    name: vector-helm-chart-value-overrides
    valuesKey: values.yaml