apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vector
commonLabels:
  app.kubernetes.io/managed-by: flux
resources:
  # - secrets.sop.yaml 
  - configmap.yaml
  - helmrelease.yaml