apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  chart:
    spec:
      chart: cloudflare-tunnel
      version: 0.3.2
      sourceRef:
        kind: HelmRepository
        name: cloudflare
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: cloudflared
  valuesFrom:
  - kind: ConfigMap
    name: cloudflared-config-map
    valuesKey: values.yaml
  - kind: Secret
    name: cloudflared-secrets
    valuesKey: credentials.json