apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kyverno
      version: 1.14.0
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: kyverno
  valuesFrom:
  - kind: ConfigMap
    name: kyverno-config-map
    valuesKey: values.yaml