apiVersion: v1
kind: ConfigMap
metadata:
  name: seafile-env
  namespace: seafile
data:
  TIME_ZONE: "UTC"
  SEAFILE_LOG_TO_STDOUT: "false"
  SITE_ROOT: "/"
  ENABLE_SEADOC: "false"
  SEADOC_SERVER_URL: "https://seafile.oglesby.io/sdoc-server"
  SEAFILE_SERVER_HOSTNAME: "seafile.oglesby.io"
  SEAFILE_SERVER_PROTOCOL: "http"

  SEAFILE_MYSQL_DB_HOST: "mariadb"
  SEAFILE_MYSQL_DB_PORT: "3306"
  SEAFILE_MYSQL_DB_USER: "seafile"
  SEAFILE_MYSQL_DB_CCNET_DB_NAME: "ccnet_db"
  SEAFILE_MYSQL_DB_SEAFILE_DB_NAME: "seafile_db"
  SEAFILE_MYSQL_DB_SEAHUB_DB_NAME: "seahub_db"

  CACHE_PROVIDER: "redis" 

  REDIS_HOST: "redis"
  REDIS_PORT: "6379"

  USE_S3_STORAGE: "false"
  S3_STORAGE_BACKEND_CONFIG: ""
  S3_COMMIT_BUCKET: ""
  S3_FS_BUCKET: ""
  S3_BLOCK_BUCKET: ""
  S3_KEY_ID: ""
  S3_USE_V4_SIGNATURE: "true"
  S3_AWS_REGION: "us-east-1"
  S3_HOST: ""
  S3_USE_HTTPS: "true"
  S3_PATH_STYLE_REQUEST: "false"

  NOTIFICATION_SERVER_URL: ""

env:
  - name: INIT_SEAFILE_ADMIN_EMAIL
    valueFrom:
      secretKeyRef:
        name: seafile-secrets
        key: INIT_SEAFILE_ADMIN_EMAIL