apiVersion: v1
kind: Service
metadata:
  name: seafile
  namespace: media
spec:
  selector:
    app: seafile
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: seafile-ui
  type: ClusterIP