apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ersatztv-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 8Gi