apiVersion: v1
kind: Service
metadata:
  name: ersatztv
  namespace: media
spec:
  selector:
    app: ersatztv
  ports:
    - port: 8409
      targetPort: 8409
      protocol: TCP
      name: ersatztv-ui
  type: ClusterIP