apiVersion: apps/v1
kind: Deployment
metadata:
  name: run-python
  namespace: mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: run-python
  template:
    metadata:
      labels:
        app: run-python
    spec:
      containers:
        - name: run-python
          image: ghcr.io/0x4272616e646f6e/mcp-run-python:2025.05
          ports:
            - containerPort: 3001
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "1"
              memory: "1Gi"