apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-cpp
  namespace: llm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama-cpp
  template:
    metadata:
      labels:
        app: llama-cpp
    spec:
      initContainers:
        - name: model-downloader
          image: alpine:latest
          command:
          - sh
          - -c
          - |
            apk add --no-cache curl && \
            echo "Checking if model exists..." && \
            if [ ! -f /models/gemma3.gguf ]; then
              echo "Downloading model..."
              curl -L -o /models/gemma3.gguf "https://huggingface.co/ggml-org/gemma-3-4b-it-GGUF/resolve/main/gemma-3-4b-it-Q4_K_M.gguf?download=true"
            else
              echo "Model already exists, skipping download."
            fi
          volumeMounts:
            - name: models
              mountPath: /models
      containers:
        - name: llama-cpp
          image: ghcr.io/ggml-org/llama.cpp:server-intel
          args:
          - "-m"
          - "/models/gemma3.gguf"
          - "--port"
          - "3000"
          - "--host"
          - "0.0.0.0"
          - "--ctx-size"
          - "4096"
          - "--batch-size"
          - "256"
          - "--n-gpu-layers"
          - "34"
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
          - name: SYCL_DEVICE_FILTER
            value: "level_zero:gpu"
          - name: GGML_SYCL_DISABLE_GRAPH
            value: "1"
          - name: GGML_SYCL_FORCE_MMQ
            value: "1"
          - name: GGML_SYCL_DISABLE_OPT
            value: "0"
          - name: GGML_SYCL_DEBUG
            value: "0"
          - name: ZES_ENABLE_SYSMAN
            value: "1"
          volumeMounts:
            - name: models
              mountPath: /models
          resources:
            requests:
              cpu: "2"
              memory: "2Gi"
            limits:
              cpu: "12"
              memory: "8Gi"
              gpu.intel.com/i915: "1"
      volumes:
        - name: models
          persistentVolumeClaim:
            claimName: llama-cpp-models