apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamevault
  namespace: games
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gamevault
  template:
    metadata:
      labels:
        app: gamevault
    spec:
      runtimeClassName: youki
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      automountServiceAccountToken: false
      containers:
        - name: gamevault
          image: docker.io/phalcode/gamevault-backend:latest
          imagePullPolicy: Always
          environment:
            - name: DB_HOST
              value: postgres
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: gamevault-secrets
                  key: POSTGRES_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gamevault-secrets
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: config
              mountPath: /media
              subPath: media
            - name: config
              mountPath: /files
              subPath: files
        - name: postgres
          image: docker.io/postgres:17
          imagePullPolicy: Always
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: gamevault-secrets
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gamevault-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: gamevault
          ports:
            - containerPort: 5432
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          volumeMounts:
            - name: db
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: gamevault-config
        - name: db
          persistentVolumeClaim:
            claimName: gamevault-db
