apiVersion: v1
kind: Service
metadata:
  name: gamevault
  namespace: games
spec:
  selector:
    app: gamevault
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: gamevault
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: gamevault-postgres
  namespace: games
spec:
  selector:
    app: gamevault-postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP