apiVersion: v1
kind: Service
metadata:
  name: gamevault
  namespace: games
spec:
  selector:
    app: gamevault
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: gamevault
  type: ClusterIP