apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: trivy
  namespace: monitoring
spec:
  chart:
    spec:
      chart: trivy
      version: 0.25.0
      sourceRef:
        kind: HelmRepository
        name: aqua
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: trivy
  valuesFrom:
  - kind: ConfigMap
    name: trivy-config-map
    valuesKey: values.yaml