apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: headlamp
  namespace: monitoring
spec:
  chart:
    spec:
      chart: headlamp
      version: 0.30.0
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: headlamp
  valuesFrom:
  - kind: ConfigMap
    name: headlamp-config-map
    valuesKey: values.yaml