apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncthing
  namespace: fileshare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncthing
  template:
    metadata:
      labels:
        app: syncthing
    spec:
      runtimeClassName: youki
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      automountServiceAccountToken: false
      containers:
        - name: syncthing
          image: lscr.io/linuxserver/syncthing:latest
          ports:
            - containerPort: 8384
              protocol: TCP
            - containerPort: 22000
              protocol: TCP
            - containerPort: 22000
              protocol: UDP
            - containerPort: 21027
              protocol: UDP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: fileshare
              mountPath: /data
              subPath: fileshare
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: syncthing-config
        - name: fileshare
          persistentVolumeClaim:
            claimName: fileshare