apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mcp-hub-config
  namespace: mcp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 20Gi