apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  namespace: automation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      automountServiceAccountToken: false
      containers:
        - name: homeassistant
          image: lscr.io/linuxserver/homeassistant:latest
          ports:
            - containerPort: 8123
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
              ephemeral-storage: "1Gi"
            limits:
              cpu: "500m"
              memory: "512Mi"
              ephemeral-storage: "2Gi"
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: homeassistant-config
