apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homeassistant-https
  namespace: automation
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`homeassistant.oglesby.io`)
      kind: Rule
      services:
        - name: homeassistant
          port: 8123
  tls:
    certResolver: letsencrypt
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homeassistant-http
  namespace: automation
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`homeassistant.oglesby.io`)
      kind: Rule
      middlewares:
        - name: redirect-to-https
          namespace: traefik
      services:
        - name: homeassistant
          port: 8123