apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-gpu-plugin
  namespace: kube-system
  labels:
    app: intel-gpu-plugin
spec:
  selector:
    matchLabels:
      app: intel-gpu-plugin
  template:
    metadata:
      labels:
        app: intel-gpu-plugin
    spec:
      containers:
        - name: intel-gpu-plugin
          image: docker.io/intel/intel-gpu-plugin:0.32.0
          securityContext:
            privileged: true
          args:
            - "--shared-dev-num=4"
          volumeMounts:
            - name: devfs
              mountPath: /dev/dri
              readOnly: false
            - name: kubelet-device-plugins
              mountPath: /var/lib/kubelet/device-plugins
              readOnly: false
      volumes:
        - name: devfs
          hostPath:
            path: /dev/dri
            type: Directory
        - name: kubelet-device-plugins
          hostPath:
            path: /var/lib/kubelet/device-plugins
            type: Directory